---
name: John Kane • me
description: Transform your plain text into static websites and blogs
theme: jekyll-theme-leap-day
title: John Kane
description: placeholder page on github
show_downloads: false
